#! /bin/bash

set -e
set -o pipefail

. ~/.bash_aliases
shopt -s expand_aliases

ciao

#
# download data
#

. src/functions.bash

mkdir -p data
cd data
for o in $(obsids)
do
    case $o in
	78377 | 78427)
	    continue
	    ;;
	*) ;;
    esac

    files=evt1,bpix,msk,flt,asol,dtf
    download_chandra_obsid $o $files
done
