#! /bin/bash

. ~/.bash_aliases
shopt -s expand_aliases

ciao

#
# download data
#

. src/functions.bash

mkdir -p data
cd data
for o in $(obsids)
do
    files=evt1,bpix,msk,flt,asol,dtf
    download_chandra_obsid $o $files
done
