#! /bin/bash

. ~/.bash_aliases
shopt -s expand_aliases

ciao

cd ./data/28427/tg_reprocess

evt2_orig=./hrcf28427N002_evt2.fits.orig
pha2_orig=./hrcf28427N002_pha2.fits.orig

[[ -f $evt2_orig && -f $pha2_orig ]] || {
    echo "oops" 1>&2
    exit 1
}

declare -A time base

time=(
    [old]=834518958.91906822:834524996.16946101
    [new]=834525190.91947365:834528969.06972170
)

base=(
    [old]=oldHV
    [new]=newHV
)

for hv in "${!time[@]}"
do
    evt2="evt2.fits.${base[$hv]}"
    pha2="pha2.fits.${base[$hv]}"

    echo dmcopy "${evt2_orig}[time=${time[$hv]}]" "$evt2" cl+
    echo dmappend "${evt2_orig}[region][subspace -time]" "$evt2"
    echo tgextract "infile=$evt2" "outfile=$pha2" \
	      tg_srcid_list=all \
	      tg_part_list=header_value \
	      inregion_file=CALDB \
	      tg_order_list=-1,1,-2,2,-3,3 \
	      cl+ \
	      outfile_type=pha_typeII \
	      ancrfile=none \
	      respfile=none
    echo ln -fs $evt2 "${evt2_orig%.*}"
    echo ln -fs $pha2 "${pha2_orig%.*}"

    dmcopy "${evt2_orig}[time=${time[$hv]}]" "$evt2" cl+
    dmappend "${evt2_orig}[region][subspace -time]" "$evt2"
    tgextract "infile=$evt2" "outfile=$pha2" \
	      tg_srcid_list=all \
	      tg_part_list=header_value \
	      inregion_file=CALDB \
	      tg_order_list=-1,1,-2,2,-3,3 \
	      cl+ \
	      outfile_type=pha_typeII \
	      ancrfile=none \
	      respfile=none
    ln -fs $evt2 "${evt2_orig%.*}"
    ln -fs $pha2 "${pha2_orig%.*}"
    echo -e "Processed $hv HV, press ENTER to continue..."
    read
done
  
