#! /bin/bash

. ~/.bash_aliases
shopt -s expand_aliases

ciao

. src/functions.bash

tgreprocess=/data/legs/rpete/flight/dev/tg_reprocess

# whether to force reprocessing if tg_reprocess outdir already exists
force=1

for src in $(sources)
do
    for o in $(source2obsids $src)
    do
	outdir=tg_reprocess
        logfile=data/$src/$o/tg_reprocess.log
	outdirfull=data/$src/$o/$outdir

	[ -f $outdirfull/*_pha2.fits -a $force -eq 0 ] && continue

	orders=
	badpix='--badpix CALDB'

        instruments "$o" | grep -qi hrc-s || continue

	instruments "$o" | grep -qi hrc-s && { orders='--orders 3'; }

	#perl $tgreprocess --nogrmf $orders $badpix --pifilter none --outdir $outdir data/$src/$o 2>&1 | tee $logfile

        # expand the source and background regions for offaxis I observations
        [ $o -eq 1516 -o $o -eq 1004 -o $o -eq 1005 -o \
          $o -eq 2601 -o $o -eq 2603 -o $o -eq 18415 ] && {

            evt2=$(ls $outdirfull/hrcf*${o}N*_evt2.fits)
            pha2=$(ls $outdirfull/hrcf*${o}N*_pha2.fits)

            echo punlearn 'tgextract' | tee -a $logfile
            punlearn 'tgextract'

            echo tgextract \
                "infile=$evt2" \
                "outfile=$pha2" \
                outfile_type=pha_typeII \
                tg_srcid_list=all \
                tg_part_list=header_value \
                tg_order_list=-1,1 \
                ancrfile=none \
                respfile=none \
                min_tg_d=-0.007 \
                max_tg_d=0.007 \
                max_upbkg_tg_d=0.035 \
                clobber=yes | tee -a $logfile

            tgextract \
                "infile=$evt2" \
                "outfile=$pha2" \
                outfile_type=pha_typeII \
                tg_srcid_list=all \
                tg_part_list=header_value \
                tg_order_list=-1,1 \
                ancrfile=none \
                respfile=none \
                min_tg_d=-0.007 \
                max_tg_d=0.007 \
                max_upbkg_tg_d=0.035 \
                clobber=yes 2>&1 | tee -a $logfile
        }


	instruments "$o" | grep -qi hrc-s && {
	    outdir=tg_reprocess_pifilter
            logfile=data/$src/$o/tg_reprocess_pifilter.log
	    outdirfull=data/$src/$o/$outdir

	    [ -f $outdirfull/*_pha2.fits -a $force -eq 0 ] ||

		perl $tgreprocess --pifilter pi --nogrmf $orders $badpix --outdir $outdir data/$src/$o 2>&1 | tee $logfile

	}
	rm -f data/$src/$o/$outdir/*_evt1{a,}.fits

    done
done

# after this is done, scan images to make sure they are all on-axis
false && {
    for src in $(sources)
    do
	for o in $(source2obsids "$src")
	do
	    f=$(ls data/"$src"/"$o"/tg_reprocess/*_evt2.fits)
	    echo "$f"
	    ds9 "$f" -bin factor 32 -scale mode 99.5 -cmap heat -scale sqrt
	done
    done
}

# to see which HRC-I observations were off-axis...so far they are 1516, 1004, 1005, 2601, 2603, 18415
#obsids=`grep -i hrc-i obsids_hz43 | cut -f 1`
#for o in $obsids; do echo $o; ds9 -cmap Heat -zoom to fit -scale log -scale mode 99.5 data/hz43/$o/tg_reprocess/*_evt2.fits -bin factor 32 32; done

